/*
 * Gavin Scott
   Multiple choice quiz for unit one summative
   October 12th
 */

/**
 *
 * @author gasco1246
 */
public class MultipleChoiceQuizSUMMgui extends javax.swing.JDialog {

    /**
     * Creates new form MultipleChoiceQuizSUMMgui
     */
    //global counters declared
    double numGuess, numCorrect, percCorrect = 0;
    int question = 0;
    //Declaration of questions
    
    String questionOne = "How much maple syrup was stolen in the Maple syrup heist of 2012?\n" +
    "a) 100 tons\n" +
    "b) 300 tons\n" +
    "c) 1000 tons\n" +  
    "d) 3000 tons\n" +
    "\n" +
    "Type the letter of your answer";
    
    String questionTwo = "What is the capital of Malaysia?\n"+
    "a) Beijing\n"+
    "b) Taipei\n"+
    "c) Kuala Lumpur\n"+
    "d) Jakarta\n"+
    "\n" +
    "Type the letter of your answer";
    
    String questionThree = "Ursus Maritimus is the latin name for what animal\n"+
    "a) Polynesian Sparrow\n"+
    "b) Maritime Wolf\n"+
    "c) Polar Bear\n"+
    "d) Arctic Fox\n"+
    "\n" +
    "Type the letter of your answer";
    
    String questionFour = "What was the last manned mission to the moon\n"+
    "a) Apollo 13\n"+
    "b) Soyuz 18\n"+
    "c) Apollo 18\n"+
    "d) Apollo 17\n"+
    "\n" +
    "Type the letter of your answer";
    
    String questionFive = "What are the ends of shoelaces called?\n"+
    "a) Ends\n"+
    "b) Aglets\n"+
    "c) EZ lacerz\n"+
    "d) None of the above, this is a stupid question\n"+
    "\n" +
    "Type the letter of your answer";
    public MultipleChoiceQuizSUMMgui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        inputField = new javax.swing.JTextField();
        numCorrectLabel = new javax.swing.JLabel();
        percCorrectLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("BloodyMurder BB", 0, 24)); // NOI18N
        Title.setText("Death inducing exam of doom...");

        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("FuturaTEE", 0, 14)); // NOI18N
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        inputField.setToolTipText("");
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        numCorrectLabel.setText("Number Correct: ");

        percCorrectLabel.setText("Percent Correct: ");

        jLabel5.setText("What is your answer:");

        submitButton.setText("Submit");
        submitButton.setToolTipText("");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Start");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(66, 66, 66)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(percCorrectLabel)
                                    .addComponent(numCorrectLabel))
                                .addGap(0, 90, Short.MAX_VALUE))
                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButton)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(numCorrectLabel)
                        .addGap(18, 18, 18)
                        .addComponent(percCorrectLabel)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //define input
        String text = inputField.getText();
        
        //check answer
        if(question == 1){
            if(text.equals("d")){
                outputArea.setText("Correct, push next question");
                numGuess++;
                numCorrect++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
            else{
                outputArea.setText("Incorrect, push next question");
                numGuess++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
        }
        else if(question == 2){
            if(text.equals("c")){
                outputArea.setText("Correct, push next question");
                numGuess++;
                numCorrect++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
            else{
                outputArea.setText("Incorrect, push next question");
                numGuess++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
        }
        else if(question == 3){
            if(text.equals("c")){
                outputArea.setText("Correct, push next question");
                numGuess++;
                numCorrect++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
            else{
                outputArea.setText("Incorrect, push next question");
                numGuess++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
        }
        else if(question == 4){
            if(text.equals("d")){
                outputArea.setText("Correct, push next question");
                numGuess++;
                numCorrect++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
            else{
                outputArea.setText("Incorrect, push next question");
                numGuess++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
        }
        else if(question == 5){
            if(text.equals("b")){
                outputArea.setText("Correct, push next question");
                numGuess++;
                numCorrect++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
            else{
                outputArea.setText("Incorrect, push next question");
                numGuess++;
                percCorrect = numCorrect/numGuess*100;
                numCorrectLabel.setText("Number Correct: "+numCorrect);
                percCorrectLabel.setText("Percent Correct: "+ Math.round(percCorrect));
                
            }
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed
 
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        //change button from start to next
        nextButton.setText("Next Question");
        
        //choose question 
        question = (int)Math.round(Math.random()*4+1);
        
        //set question text
        if (question == 1){
            outputArea.setText(questionOne);
            
        }
        else if (question == 2){
            outputArea.setText(questionTwo);
            
        }
        else if (question == 3){
            outputArea.setText(questionThree);
            
        }
        else if (question == 4){
            outputArea.setText(questionFour);
            
        }
        else if (question == 5){
            outputArea.setText(questionFive);
            
        }
        
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizSUMMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizSUMMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizSUMMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuizSUMMgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MultipleChoiceQuizSUMMgui dialog = new MultipleChoiceQuizSUMMgui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel numCorrectLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel percCorrectLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
